documentation:
  - changed-files:
      - any-glob-to-any-file: 'document/**/*.md'

foundational:
  - changed-files:
      - any-glob-to-any-file: [ 'unicorn-core/src/main/java/**/*', 'unicorn-beans/src/main/java/**/*' ]

# Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: 'main'
