server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_no_trans: true
    open-in-view: true
    hibernate:
      ddl-auto: none
  # use virtual threads in Spring Boot 3.2 + Java 21
  threads:
    virtual:
      enabled: true

  #配置数据源
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:10.211.55.145}:${DB_PORT:}/${DB_NAME:}
    username: ${DB_USER:}
    password: ${DB_PWD:}

    hikari:
      # When the pool reaches this size, and no idle connections are available, calls to getConnection() will block for up to connectionTimeout milliseconds before timing out. Please read about pool sizing. Default: 10
      maximum-pool-size: 10
      pool-name: Authorize-Server
      connection-test-query: SELECT 1

  # cache配置
  cache:
    type: redis
  # redis配置
  data:
    redis:
      url: redis://redis-psd@10.211.55.145:6379
      timeout: 2000
      database: 4
