version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql/log:/var/log/mysql #日志文件挂载
  mysql-slave01:
    image: mysql:latest
    container_name: mysql-slave01
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3308:3306
    volumes:
      - /mydata/mysql-slave01/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql-slave01/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql-slave01/log:/var/log/mysql #日志文件挂载
    depends_on:
      - mysql
    links:
      - mysql
  mysql-slave02:
    image: mysql:latest
    container_name: mysql-slave02
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3310:3306
    volumes:
      - /mydata/mysql-slave02/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql-slave02/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql-slave02/log:/var/log/mysql #日志文件挂载
    depends_on:
      - mysql
    links:
      - mysql
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass "redis-psd"
    volumes:
      - /mydata/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    command: redis-server --slaveof redis 6379 --masterauth "redis-psd" --appendonly yes --requirepass "redis-psd"
    volumes:
      - /mydata/redis-slave1/data:/data #数据文件挂载
    depends_on:
      - redis
    ports:
      - 6378:6379
    links:
      - redis
  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    command: redis-server --slaveof redis 6379 --masterauth "redis-psd" --appendonly yes --requirepass "redis-psd"
    volumes:
      - /mydata/redis-slave2/data:/data #数据文件挂载
    depends_on:
      - redis
    ports:
      - 6380:6379
    links:
      - redis
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /mydata/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - /mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - /mydata/nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80
  rabbitmq:
    image: rabbitmq:3.9.9-management
    container_name: rabbitmq
    volumes:
      - /mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - /mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  rabbitmq-p2:
    image: rabbitmq:3.9.9-management
    container_name: rabbitmq-p2
    volumes:
      - /mydata/rabbitmq-p2/data:/var/lib/rabbitmq #数据文件挂载
      - /mydata/rabbitmq-p2/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5674:5672
      - 15674:15672
  rabbitmq-p3:
    image: rabbitmq:3.9.9-management
    container_name: rabbitmq-p3
    volumes:
      - /mydata/rabbitmq-p3/data:/var/lib/rabbitmq #数据文件挂载
      - /mydata/rabbitmq-p3/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5676:5672
      - 15676:15672
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.14.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
