server:
  port: 8082
  http2:
    enabled: true
  undertow:
    threads:
      io: 6
      worker: 48
    buffer-size: 1024
    direct-buffers: true

  #  server.http2.enabled=true
  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
  # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
  #  server.undertow.threads.io= 6
  # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
  # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
  #  server.undertow.threads.worker= 48
  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
  # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
  #server.undertow.buffer-size= 1024
  # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
  #server.undertow.buffers-per-region= 1024
  # 是否分配的直接内存(NIO直接分配的堆外内存)
  #  server.undertow.direct-buffers= true

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_no_trans: true
    open-in-view: true

#  # 全局懒加载。
#  main:
#    lazy-initialization: true

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

  #七牛云
  #qiniu:
  # 文件大小 /M
#  max-size: 15

#邮箱验证码有效时间/秒
#code:
#  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

#
logging:
  config: classpath:logback-spring.xml
