name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '18'
          distribution: 'corretto'
          check-latest: true

      - name: Build Core
        run: mvn -B install --file pom.xml
      # - name: Build Valentine's Day
      #   run: mvn -B package --file valentine-starter/pom.xml
      - name: Build Docker image
        run: $ mvn -B spring-boot:build-image --file valentine-starter/pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
