name: Docker Image CI

on:
  push:
    branches: [ "dev_3.x" ]
  pull_request:
    branches: [ "dev_3.x" ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'corretto'
          check-latest: true
        # add custom dependency to env
      - name: Extra Custom Env
        run: mvn install:install-file -DgroupId=org.projectlombok -DartifactId=lombok -Dversion=1.18.25 -Dpackaging=jar -Dfile=ex-lib/lombok-1.18.25.jar

      - name: Build Core
        run: mvn -B install --file pom.xml
      # - name: Build Valentine's Day
      #   run: mvn -B package --file valentine-starter/pom.xml
      - name: Build the Docker image
        run: mvn -B spring-boot:build-image --file valentine-starter/pom.xml
