name: Docker Image CI

on:
  push:
    branches: [ "main", "delta-oauth2.0" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #  https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Installing-custom-Java-package-type
      - run: |
          download_url="https://download.oracle.com/graalvm/20/latest/graalvm-jdk-20_macos-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '20'
          architecture: x64
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage

      - name: Publish 2 MavenLocal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal

      - name: Remove module-info
        run: rm -rf unicorn-starter/src/main/java/module-info.java

      - name: Build Unicorn-Starter
        run: mvn -B package --file unicorn-starter/pom.xml -P jigsaw
