# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

# on:
#   release:
#     types: [created]
    
on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v3.0.0
      with:
        package-version-ids: 'PV_lADOFOUqEc4AF-yqzgFWQ3s, PV_lADOFOUqEc4ADKq8zgFWQ6Y, PV_lADOFOUqEc4ADKq3zgFWQ60, PV_lADOFOUqEc4ADKq2zgFWQ7U, PV_lADOFOUqEc4ADKq1zgFWQ6A, PV_lADOFOUqEc4ADKq0zgFWQ3k, PV_lADOFOUqEc4ADKqzzgFWQ3g'
        min-versions-to-keep: 1

    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
